os: linux
dist: bionic
group: travis_latest
language: shell

if: |
  branch = master AND ! commit_message =~ /readme.md/ AND ! commit_message =~ /docker-compose.yml/
  OR type = cron

services:
  - docker

env:

  global:
    - BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    - BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
    - DOCKER_DESCRIPTION="reverse proxy and load balancer"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="traefik"
    - DOCKER_URL="https://traefik.io/"
    - OS_NAME="ubuntu"
    - OS_CODENAME="$(curl -fsSL https://raw.githubusercontent.com/tianon/docker-brew-ubuntu-core/master/rolling)"
    - SCHEMA_VERSION="1.0"
    - VCS_REF="$(git rev-parse --short HEAD)"
    - VCS_URL="$(git remote get-url origin | head -c-5)"
    - DOCKER_TAG="latest"
    - DOCKER_VERSION="$(sudo bash travis/get_version.sh)"

before_install:
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1
  - sudo bash travis/docker.sh
  - sudo docker version
  
install:
  - sudo docker run --privileged linuxkit/binfmt:v0.7
  - sudo docker run --privileged -d -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/arm --oci-worker-platform linux/armhf --oci-worker-platform linux/arm64 --oci-worker-platform linux/amd64
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234

before_script:
  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' dockerfiles/*
  - chmod 0544 rootfs/usr/local/bin/docker_entrypoint.sh
  - curl -sSL -o traefik-arm.tar.gz "https://github.com/containous/traefik/releases/download/v${DOCKER_VERSION}/traefik_v{DOCKER_VERSION}_linux_armv7.tar.gz"
  #- chmod 0500 traefik-arm
  - curl -sSL -o traefik-arm64.tar.gz "https://github.com/containous/traefik/releases/download/v${DOCKER_VERSION}/traefik_v{DOCKER_VERSION}_linux_arm64.tar.gz"
  #- chmod 0500 traefik-arm64
  - curl -sSL -o traefik-amd64.tar.gz "https://github.com/containous/traefik/releases/download/v${DOCKER_VERSION}/traefik_v{DOCKER_VERSION}_linux_amd64.tar.gz"
  #- chmod 0500 traefik-amd64

script:
  - sudo bash travis/build.sh
  - sudo bash travis/deploy.sh

after_success:

notifications:
  email:
    on_success: never
    on_failure: change
