version: '2.4'

networks:

  frontend_bridge:
    external:
      name: frontend

  backend_bridge:
    external:
      name: backend


services:

  traefik:
    image: stlouisn/traefik
    container_name: traefik
    hostname: traefik
    environment:
      - LC_ALL=C.UTF-8
      - TZ=UTC
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.DOMAIN_NAME
      - traefik.docker.network=frontend
      - traefik.port=8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/config:/etc/traefik
    mem_limit: 50M
    memswap_limit: 50M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: "traefik healthcheck"
      start_period: 30s
      interval: 60s
      timeout: 10s
      retries: 5
    networks:
      - frontend_bridge
    ports:
      - 80:80
      - 443:443

  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    environment:
      - LC_ALL=C.UTF-8
      - TZ=America/Halifax
    labels:
      - traefik.enable=true
      - traefik.backend=portainer
      - traefik.frontend.rule=Host:portainer.DOMAIN_NAME
      - traefik.docker.network=frontend
      - traefik.port=9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    mem_limit: 50M
    memswap_limit: 50M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - frontend_bridge
    depends_on:
      traefik:
        condition: service_healthy
