# Log level
#
# Optional
# Default: "ERROR"
#
# Accepted values, in order of severity: "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
# Messages at and above the selected level will be logged.
#
logLevel = "INFO"

# Enable debug mode
# This will install HTTP handlers to expose Go expvars under /debug/vars and pprof profiling data under /debug/pprof.
# Additionally, the log level will be set to DEBUG.
#
# Optional
# Default: false
#
debug = false

# Send anonymous usage data
#
# Optional
# Default: false
#
sendAnonymousUsage = false

# Periodically check if a new version has been released
#
# Optional
# Default: true
#
checkNewVersion = false

# Entrypoints to be used by frontends that do not specify any entrypoint
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http", "https"]

[api]

# Enabled Dashboard
#
# Optional
# Default: true
#
dashboard=true

# Name of the dashboard entry point
#
entryPoint = "traefik"

[ping]

# Name of the healthcheck entry point
#
entryPoint = "traefik"

[entryPoints]

    [entryPoints.http]
    address = ":80"

    [entryPoints.http.redirect]
    entryPoint = "https"

    [entryPoints.https]
    address = ":443"

    [entryPoints.https.tls]

    [entryPoints.traefik]
    address = ":8080"
        [entryPoints.traefik.auth]
            [entryPoints.traefik.auth.basic]
            users = [
                "admin:INSERT_HASHED_PASSWORD"
            ]

[acme]

    email = "INSERT_EMAIL_ADDRESS"
    storage = "/etc/traefik/acme.json"
    entryPoint = "https"
    onDemand = false
    onHostRule = true

[docker]

    # Docker server endpoint. Can be a tcp or a unix socket endpoint
    #
    endpoint = "unix:///var/run/docker.sock"

    # Default domain. Can be overridden by setting the "traefik.domain" label on a container
    #
    domain = "INSERT_DOMAIN_NAME"

    # Enable watch docker changes
    #
    watch = true

    # Ignore containers by default
    # Containers that don't have "traefik.enable=true" will be ignored
    #
    exposedbydefault = false
